image: condaforge/miniforge3

stages:
  - buildtest
  - deploy

before_script:
    - conda create -n pysst
    - source activate pysst

buildtest:
 stage: buildtest
 script:
    - pip install -e .[dev]
    - cd tests
    - python -m pytest --cache-clear
    - python -m pytest --verbose --cov=pysst --cov-config=.coveragerc
artifacts:
  paths:
    - tests/coverage.xml 
  expire_in: 1 week


deploy:
  stage: deploy
  script: echo "Not implemented yet"
  environment: production
