image: condaforge/miniforge3

stages:
  - lint
  - buildtest
  - deploy

before_script:
    - conda create -n pysst
    - source activate pysst
    - pip install ruff

# Ignore F401 linting error (imported package unused) because it bitches about unused 
# __init__.py imports.
lint:
 stage: lint
 script:
    - ruff check --ignore F401 ./pysst

buildtest:
 stage: buildtest
 script:
    - pip install -e .[dev]
    - cd tests
    - python -m pytest --cache-clear
    - python -m pytest --verbose --cov=pysst --cov-config=.coveragerc
    - coverage report
    - coverage xml
 coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
 artifacts:
    paths:
      - pysst/tests/coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: pysst/tests/coverage.xml
    expire_in: 1 week



deploy:
  stage: deploy
  script: echo "Not implemented yet"
  environment: production
