[project]
name = "geost"
version = "0.2.1"
description = "GeoST is the Python interface for subsurface data of The Netherlands"
authors = ["Erik van Onselen <erik.vanonselen@deltares.nl>", 
        "Bas Knaake <bas.knaake@gmail.com>", 
        "Tommer Vermaas <tommer.vermaas@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
install = "python -m pip install --no-deps --editable ."
test = { depends_on = ["install"], cmd = "python -m pytest --verbose --cov=geost --cov-report xml --cov-report term"}
docs = "sphinx-build -b html docs ./docs/build"
format = "black ."
lint = { depends_on = ["install"], cmd = "ruff check --fix ./geost"}

[dependencies]
python = ">=3.12"
numpy = "*"
pandas = ">=2.0.1"
pyarrow = "*"
lxml = "*"
pyproj = "*"
geopandas = "*"
xlrd = "*"
openpyxl = "*"
shapely = ">=2.0.1"
pyvista = "*"
black = "*"
pytest = ">=8.1.1,<8.2"
pytest-cov = "*"
ruff = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pip = ">=24.0,<25"
rioxarray = ">=0.15.3,<0.16"

[feature.py312.dependencies]
python = "3.12.*"

[environments]
py312 = ["py312"]
