# CptCollection { #geost.base.CptCollection }

```python
base.CptCollection(self, header, data)
```



## Attributes

| Name | Description |
| --- | --- |
| [data](#geost.base.CptCollection.data) | The collection's data. |
| [has_inclined](#geost.base.CptCollection.has_inclined) | Boolean indicating whether there are inclined objects within the collection |
| [header](#geost.base.CptCollection.header) | The collection's header. |
| [horizontal_reference](#geost.base.CptCollection.horizontal_reference) | Coordinate reference system represented by an instance of pyproj.crs.CRS. |
| [n_points](#geost.base.CptCollection.n_points) | Number of objects in the collection. |
| [vertical_reference](#geost.base.CptCollection.vertical_reference) | Vertical datum represented by an instance of pyproj.crs.CRS. |

## Methods

| Name | Description |
| --- | --- |
| [add_header_column_to_data](#geost.base.CptCollection.add_header_column_to_data) | Add a column from the header to the data table. Useful if you e.g. add some data |
| [change_horizontal_reference](#geost.base.CptCollection.change_horizontal_reference) | Change the horizontal reference (i.e. coordinate reference system, crs) of the |
| [change_vertical_reference](#geost.base.CptCollection.change_vertical_reference) | Change the vertical reference of the collection object's surface levels |
| [check_header_to_data_alignment](#geost.base.CptCollection.check_header_to_data_alignment) | Two-way check to warn of any misalignment between the header and data |
| [get](#geost.base.CptCollection.get) | Get a subset of a collection through a string or iterable of object id(s). |
| [get_area_labels](#geost.base.CptCollection.get_area_labels) | Find in which area (polygons) the point data locations fall. e.g. to determine |
| [reset_header](#geost.base.CptCollection.reset_header) | Refresh the header based on the loaded data in case the header got messed up. |
| [select_by_condition](#geost.base.CptCollection.select_by_condition) | Select from collection.data using a manual condition that results in a boolean |
| [select_by_depth](#geost.base.CptCollection.select_by_depth) | Select data from depth constraints. If a keyword argument is not given it will |
| [select_by_length](#geost.base.CptCollection.select_by_length) | Select data from length constraints: e.g. all boreholes between 50 and 150 m |
| [select_by_values](#geost.base.CptCollection.select_by_values) | Select data based on the presence of given values in a given column. Can be used |
| [select_with_lines](#geost.base.CptCollection.select_with_lines) | Make a selection of the collection based on line geometries. |
| [select_with_points](#geost.base.CptCollection.select_with_points) | Make a selection of the collection based on point geometries. |
| [select_within_bbox](#geost.base.CptCollection.select_within_bbox) | Make a selection of the collection based on a bounding box. |
| [select_within_polygons](#geost.base.CptCollection.select_within_polygons) | Make a selection of the collection based on polygon geometries. |
| [slice_by_values](#geost.base.CptCollection.slice_by_values) | Slice rows from data based on matching condition. E.g. only return rows with |
| [slice_depth_interval](#geost.base.CptCollection.slice_depth_interval) | Slice data based on given upper and lower boundaries. This returns a new object |
| [to_csv](#geost.base.CptCollection.to_csv) | Export the data or header table to a csv file. By default the data table is |
| [to_datafusiontools](#geost.base.CptCollection.to_datafusiontools) | Export all data to the core "Data" class of Deltares DataFusionTools. Returns |
| [to_geopackage](#geost.base.CptCollection.to_geopackage) | Write header data to geopackage. You can use the resulting file to display |
| [to_geoparquet](#geost.base.CptCollection.to_geoparquet) | Write header data to geoparquet. You can use the resulting file to display |
| [to_multiblock](#geost.base.CptCollection.to_multiblock) | Create a Pyvista MultiBlock object from the data that can be used for 3D plotting |
| [to_parquet](#geost.base.CptCollection.to_parquet) | Export the data or header table to a parquet file. By default the data table is |
| [to_shape](#geost.base.CptCollection.to_shape) | Write header data to shapefile. You can use the resulting file to display |
| [to_vtm](#geost.base.CptCollection.to_vtm) | Save data as VTM (Multiblock file, an XML VTK file pointing to multiple other |

### add_header_column_to_data { #geost.base.CptCollection.add_header_column_to_data }

```python
base.CptCollection.add_header_column_to_data(column_name)
```

Add a column from the header to the data table. Useful if you e.g. add some data
to the header table, but would like to add this to each layer (row in the data
table) as well.

#### Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                    | Default    |
|-------------|--------|------------------------------------------------|------------|
| column_name | str    | Name of the column in the header table to add. | _required_ |

### change_horizontal_reference { #geost.base.CptCollection.change_horizontal_reference }

```python
base.CptCollection.change_horizontal_reference(to_epsg)
```

Change the horizontal reference (i.e. coordinate reference system, crs) of the
collection to the given target crs.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type              | Description                                                                                         | Default    |
|---------|-------------------|-----------------------------------------------------------------------------------------------------|------------|
| to_epsg | str \| int \| CRS | EPSG of the target crs. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). | _required_ |

#### Examples {.doc-section .doc-section-examples}

To change the collection's current horizontal reference to WGS 84 UTM zone 31N:

```python
>>> self.change_horizontal_reference(32631)
```

This would be the same as:

```python
>>> self.change_horizontal_reference("epsg:32631")
```

As Pyproj is very flexible, you can even use the CRS's full official name:

```python
>>> self.change_horizontal_reference("WGS 84 / UTM zone 31N")
```

### change_vertical_reference { #geost.base.CptCollection.change_vertical_reference }

```python
base.CptCollection.change_vertical_reference(to_epsg)
```

Change the vertical reference of the collection object's surface levels

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type              | Description                                                                                                                                                                                                                                                                                                   | Default    |
|---------|-------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| to_epsg | str \| int \| CRS | EPSG of the target vertical datum. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). However, it must be a vertical datum.  Some often-used vertical datums are: NAP             : 5709 MSL NL depth    : 9288 LAT NL depth    : 9287 Ostend height   : 5710  See epsg.io for more. | _required_ |

#### Examples {.doc-section .doc-section-examples}

To change the header's current vertical reference to NAP:

```python
>>> self.change_horizontal_reference(5709)
```

This would be the same as:

```python
>>> self.change_horizontal_reference("epsg:5709")
```

As the Pyproj constructors are very flexible, you can even use the CRS's full
official name instead of an EPSG number. E.g. for changing to NAP and the
Belgian Ostend height vertical datums repsectively, you can use:

```python
>>> self.change_horizontal_reference("NAP")
>>> self.change_horizontal_reference("Ostend height")
```

### check_header_to_data_alignment { #geost.base.CptCollection.check_header_to_data_alignment }

```python
base.CptCollection.check_header_to_data_alignment()
```

Two-way check to warn of any misalignment between the header and data
attributes. Two way, i.e. if header includes more objects than in the data and
if the data includes more unique objects that listed in the header.

This check is performed everytime the object is instantiated AND if any change
is made to either the header or data attributes (see their respective setters).

### get { #geost.base.CptCollection.get }

```python
base.CptCollection.get(selection_values, column='nr')
```

Get a subset of a collection through a string or iterable of object id(s).
Optionally uses a different column than "nr" (the column with object ids).

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type            | Description                                                                 | Default    |
|------------------|-----------------|-----------------------------------------------------------------------------|------------|
| selection_values | str \| Iterable | Values to select                                                            | _required_ |
| column           | str             | In which column of the header to look for selection values, by default "nr" | `'nr'`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

#### Examples {.doc-section .doc-section-examples}

self.get(["obj1", "obj2"]) will return a collection with only these objects.

Suppose we have a collection of boreholes that we have joined with geological
map units using the method
:meth:`~geost.base.PointDataCollection.get_area_labels`. We have added this data
to the header table in the column 'geological_unit'. Using:

self.get(["unit1", "unit2"], column="geological_unit")

will return a :class:`~geost.base.BoreholeCollection` with all boreholes
that are located in "unit1" and "unit2" geological map areas.

### get_area_labels { #geost.base.CptCollection.get_area_labels }

```python
base.CptCollection.get_area_labels(
    polygon_gdf
    column_name
    include_in_header=False
)
```

Find in which area (polygons) the point data locations fall. e.g. to determine
in which geomorphological unit points are located.

#### Parameters {.doc-section .doc-section-parameters}

| Name              | Type                            | Description                                                                    | Default    |
|-------------------|---------------------------------|--------------------------------------------------------------------------------|------------|
| polygon_gdf       | str \| Path \| gpd.GeoDataFrame | GeoDataFrame with polygons.                                                    | _required_ |
| column_name       | str                             | The column name to find the labels in.                                         | _required_ |
| include_in_header | bool                            | Whether to add the acquired data to the header table or not, by default False. | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                                                                                                                              |
|--------|--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | pd.DataFrame | Borehole ids and the polygon label they are in. If include_in_header = True, a column containing the generated data will be added inplace to the header. |

### reset_header { #geost.base.CptCollection.reset_header }

```python
base.CptCollection.reset_header()
```

Refresh the header based on the loaded data in case the header got messed up.

### select_by_condition { #geost.base.CptCollection.select_by_condition }

```python
base.CptCollection.select_by_condition(condition, invert=False)
```

Select from collection.data using a manual condition that results in a boolean
mask. Returns the rows in the data where the 'condition' evaluates to True.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type                          | Description                                                                                                                                                      | Default    |
|-----------|-------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| condition | list, pd.Series or array like | Boolean array like object with locations at which the values will be preserved, dtype must be 'bool' and the length must correspond with the length of the data. | _required_ |
| invert    | bool                          | If True, the selection is inverted so rows that evaluate to False will be returned. The default is False.                                                        | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                                            |
|--------|---------------------------------|------------------------------------------------------------------------|
|        | class:`~geost.base.LayeredData` | New instance containing only the data objects selected by this method. |

#### Examples {.doc-section .doc-section-examples}

Select rows in borehole data that contain a specific value:

```python
>>> boreholes.select_by_condition(boreholes["lith"]=="V")
```

Or select rows in the borehole data that contain a specific (part of) string or
strings:

```python
>>> boreholes.select_by_condition(boreholes["column"].str.contains("foo|bar"))
```

### select_by_depth { #geost.base.CptCollection.select_by_depth }

```python
base.CptCollection.select_by_depth(
    top_min=None
    top_max=None
    end_min=None
    end_max=None
)
```

Select data from depth constraints. If a keyword argument is not given it will
not be considered. e.g. if you need only boreholes that go deeper than -500 m
use only end_max = -500.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type   | Description                                                 | Default   |
|---------|--------|-------------------------------------------------------------|-----------|
| top_min | float  | Minimum elevation of the borehole/cpt top, by default None. | `None`    |
| top_max | float  | Maximum elevation of the borehole/cpt top, by default None. | `None`    |
| end_min | float  | Minimum elevation of the borehole/cpt end, by default None. | `None`    |
| end_max | float  | Maximumelevation of the borehole/cpt end, by default None.  | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### select_by_length { #geost.base.CptCollection.select_by_length }

```python
base.CptCollection.select_by_length(min_length=None, max_length=None)
```

Select data from length constraints: e.g. all boreholes between 50 and 150 m
long. If a keyword argument is not given it will not be considered.

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type   | Description                                      | Default   |
|------------|--------|--------------------------------------------------|-----------|
| min_length | float  | Minimum length of borehole/cpt, by default None. | `None`    |
| max_length | float  | Maximum length of borehole/cpt, by default None. | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### select_by_values { #geost.base.CptCollection.select_by_values }

```python
base.CptCollection.select_by_values(column, selection_values, how='or')
```

Select data based on the presence of given values in a given column. Can be used
for example to select boreholes that contain peat in the lithology column.

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type            | Description                                                                                                                                                                                              | Default    |
|------------------|-----------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| column           | str             | Name of column that contains categorical data to use when looking for values.                                                                                                                            | _required_ |
| selection_values | str \| Iterable | Value or values to look for in the column.                                                                                                                                                               | _required_ |
| how              | str             | Either "and" or "or". "and" requires all selection values to be present in column for selection. "or" will select the core if any one of the selection_values are found in the column. Default is "and". | `'or'`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

#### Examples {.doc-section .doc-section-examples}

To select boreholes where both clay ("K") and peat ("V") are present at the same
time, use "and" as a selection method:

```python
>>> boreholes.select_by_values("lith", ["V", "K"], how="and")
```

To select boreholes that can have one, or both lithologies, use or as the selection
method:

```python
>>> boreholes.select_by_values("lith", ["V", "K"], how="and")
```

### select_with_lines { #geost.base.CptCollection.select_with_lines }

```python
base.CptCollection.select_with_lines(lines, buffer, invert=False)
```

Make a selection of the collection based on line geometries.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                            | Description                                                                 | Default    |
|--------|---------------------------------|-----------------------------------------------------------------------------|------------|
| lines  | str \| Path \| gpd.GeoDataFrame | Geodataframe (or file that can be parsed to a geodataframe) to select with. | _required_ |
| buffer | float \| int                    | Buffer distance for selection geometries.                                   | _required_ |
| invert | bool                            | Invert the selection, by default False.                                     | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### select_with_points { #geost.base.CptCollection.select_with_points }

```python
base.CptCollection.select_with_points(points, buffer, invert=False)
```

Make a selection of the collection based on point geometries.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                            | Description                                                                 | Default    |
|--------|---------------------------------|-----------------------------------------------------------------------------|------------|
| points | str \| Path \| gpd.GeoDataFrame | Geodataframe (or file that can be parsed to a geodataframe) to select with. | _required_ |
| buffer | float \| int                    | Buffer distance for selection geometries.                                   | _required_ |
| invert | bool                            | Invert the selection, by default False.                                     | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### select_within_bbox { #geost.base.CptCollection.select_within_bbox }

```python
base.CptCollection.select_within_bbox(xmin, ymin, xmax, ymax, invert=False)
```

Make a selection of the collection based on a bounding box.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type         | Description                                                                                             | Default    |
|--------|--------------|---------------------------------------------------------------------------------------------------------|------------|
| xmin   | float \| int | Minimum x-coordinate of the bounding box.                                                               | _required_ |
| ymin   | float \| int | Minimum y-coordinate of the bounding box.                                                               | _required_ |
| xmax   | float \| int | Maximum x-coordinate of the bounding box.                                                               | _required_ |
| ymax   | float \| int | Maximum y-coordinate of the bounding box.                                                               | _required_ |
| invert | bool         | Invert the selection, so select all objects outside of the bounding box in this case, by default False. | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### select_within_polygons { #geost.base.CptCollection.select_within_polygons }

```python
base.CptCollection.select_within_polygons(polygons, buffer=0, invert=False)
```

Make a selection of the collection based on polygon geometries.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type                            | Description                                                                     | Default    |
|----------|---------------------------------|---------------------------------------------------------------------------------|------------|
| polygons | str \| Path \| gpd.GeoDataFrame | Geodataframe (or file that can be parsed to a geodataframe) to select with.     | _required_ |
| buffer   | float \| int                    | Optional buffer distance around the polygon selection geometries, by default 0. | `0`        |
| invert   | bool                            | Invert the selection, by default False.                                         | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

### slice_by_values { #geost.base.CptCollection.slice_by_values }

```python
base.CptCollection.slice_by_values(column, selection_values, invert=False)
```

Slice rows from data based on matching condition. E.g. only return rows with
a certain lithology in the collection object.

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type            | Description                                                                                                              | Default    |
|------------------|-----------------|--------------------------------------------------------------------------------------------------------------------------|------------|
| column           | str             | Name of column that contains categorical data to use when looking for values.                                            | _required_ |
| selection_values | str \| Iterable | Values to look for in the column.                                                                                        | _required_ |
| invert           | bool            | If True, invert the slicing action, so remove layers with selected values instead of keeping them. The default is False. | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

#### Examples {.doc-section .doc-section-examples}

Return only rows in borehole data contain sand ("Z") as lithology:

```python
>>> boreholes.slice_by_values("lith", "Z")
```

If you want all the rows that may contain everything but sand, use the "invert"
option:

```python
>>> boreholes.slice_by_values("lith", "Z", invert=True)
```

### slice_depth_interval { #geost.base.CptCollection.slice_depth_interval }

```python
base.CptCollection.slice_depth_interval(
    upper_boundary=None
    lower_boundary=None
    relative_to_vertical_reference=False
    update_layer_boundaries=True
)
```

Slice data based on given upper and lower boundaries. This returns a new object
containing only the sliced data.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type         | Description                                                                                                                                                                                                                | Default   |
|--------------------------------|--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| upper_boundary                 | float \| int | Every layer that starts above this is removed. The default is None.                                                                                                                                                        | `None`    |
| lower_boundary                 | float \| int | Every layer that starts below this is removed. The default is None.                                                                                                                                                        | `None`    |
| relative_to_vertical_reference | bool         | If True, the slicing is done with respect to any kind of vertical reference plane (e.g. "NAP", "TAW"). If False, the slice is done with respect to depth below the surface. The default is False.                          | `False`   |
| update_layer_boundaries        | bool         | If True, the layer boundaries in the sliced data are updated according to the upper and lower boundaries used with the slice. If False, the original layer boundaries are kept in the sliced object. The default is False. | `True`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                                | Description                                                                                                                                                                                                       |
|--------|-------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | New instance of the current object. | New instance of the current object containing only the selection resulting from application of this method. e.g. if you are calling this method from a Collection, you will get an instance of a Collection back. |

#### Examples {.doc-section .doc-section-examples}

Usage depends on whether the slicing is done with respect to depth below the
surface or to a vertical reference plane.

For example, select layers in boreholes that are between 2 and 3 meters below the
surface:

```python
>>> boreholes.slice_depth_interval(2, 3)
```

By default, the method updates the layer boundaries in sliced object according to
the upper and lower boundaries. To suppress this behaviour use:

```python
>>> boreholes.slice_depth_interval(2, 3, update_layer_boundaries=False)
```

Slicing can also be done with respect to a vertical reference plane like "NAP".
For example, to select layers in boreholes that are between -3 and -5 m NAP, use:

```python
>>> boreholes.slice_depth_interval(-3, -5, relative_to_vertical_reference=True)
```

### to_csv { #geost.base.CptCollection.to_csv }

```python
base.CptCollection.to_csv(outfile, data_table=True, **kwargs)
```

Export the data or header table to a csv file. By default the data table is
exported.

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type        | Description                                                                  | Default    |
|------------|-------------|------------------------------------------------------------------------------|------------|
| outfile    | str \| Path | Path to csv file to be written.                                              | _required_ |
| data_table | bool        | If True, the data table is exported. If False, the header table is exported. | `True`     |
| **kwargs   |             | pd.DataFrame.to_csv kwargs. See relevant Pandas documentation.               | `{}`       |

#### Examples {.doc-section .doc-section-examples}

Export the data table:

```python
>>> collection.to_parquet("example.csv")
```

Export the header table:

```python
>>> collection.to_parquet("example.csv", data_table=False)
```

### to_datafusiontools { #geost.base.CptCollection.to_datafusiontools }

```python
base.CptCollection.to_datafusiontools(
    columns
    outfile=None
    encode=False
    relative_to_vertical_reference=True
)
```

Export all data to the core "Data" class of Deltares DataFusionTools. Returns
a list of "Data" objects, one for each data object that is exported. This list
can directly be used within DataFusionTools. If out_file is given, the list of
Data objects is saved to a pickle file.

For DataFusionTools visit:
https://bitbucket.org/DeltaresGEO/datafusiontools/src/master/

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type        | Description                                                                                                                                                                                                                                                                                                                                                                                                                      | Default    |
|--------------------------------|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| columns                        | List\[str\] | Which columns in the data to include for the export. These will become variables in the DataFusionTools "Data" class.                                                                                                                                                                                                                                                                                                            | _required_ |
| outfile                        | str \| Path | If a path to outfile is given, the data is written to a pickle file.                                                                                                                                                                                                                                                                                                                                                             | `None`     |
| encode                         | bool        | If True, categorical data columns are encoded to additional binary columns (all possible values become a seperate feature that is 0 or 1). The default is False. Warning: if there is a large number of possible categories, many columns with categorical data or both, the export process may become slow and may consume a large amount memory. Please consider carefully which categorical data columns need to be included. | `True`     |
| relative_to_vertical_reference | bool        | If True, the depth of all data objects will converted to a depth with respect to a reference plane (e.g. "NAP", "Ostend height"). If False, the depth will be kept as original in the "top" and "bottom" columns which is in meter below the surface. The default is True.                                                                                                                                                       | `True`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                       |
|--------|--------------|---------------------------------------------------|
|        | List\[Data\] | List containing the DataFusionTools Data objects. |

### to_geopackage { #geost.base.CptCollection.to_geopackage }

```python
base.CptCollection.to_geopackage(outfile, **kwargs)
```

Write header data to geopackage. You can use the resulting file to display
borehole locations in GIS for instance.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type        | Description                                                            | Default    |
|----------|-------------|------------------------------------------------------------------------|------------|
| outfile  | str \| Path | Path to geopackage to be written.                                      | _required_ |
| **kwargs |             | gpd.GeoDataFrame.to_file kwargs. See relevant GeoPandas documentation. | `{}`       |

### to_geoparquet { #geost.base.CptCollection.to_geoparquet }

```python
base.CptCollection.to_geoparquet(outfile, **kwargs)
```

Write header data to geoparquet. You can use the resulting file to display
borehole locations in GIS for instance. Please note that Geoparquet is supported
by GDAL >= 3.5. For Qgis this means QGis >= 3.26

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type        | Description                                                            | Default    |
|----------|-------------|------------------------------------------------------------------------|------------|
| outfile  | str \| Path | Path to shapefile to be written.                                       | _required_ |
| **kwargs |             | gpd.GeoDataFrame.to_parquet kwargs. See relevant Pandas documentation. | `{}`       |

### to_multiblock { #geost.base.CptCollection.to_multiblock }

```python
base.CptCollection.to_multiblock(
    data_columns
    radius=1
    vertical_factor=1.0
    relative_to_vertical_reference=True
)
```

Create a Pyvista MultiBlock object from the data that can be used for 3D plotting
and other spatial analyses.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type               | Description                                                                                                                                                                                                                                                              | Default    |
|--------------------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| data_columns                   | str \| List\[str\] | Name or names of data columns to include for visualisation. Can be columns that contain an array of floats, ints and strings.                                                                                                                                            | _required_ |
| radius                         | float              | Radius of the cylinders in m in the MultiBlock. The default is 1.                                                                                                                                                                                                        | `1`        |
| vertical_factor                | float              | Factor to correct vertical scale. For example, when layer boundaries are given in cm, use 0.01 to convert to m. The default is 1.0, so no correction is applied. It is not recommended to use this for vertical exaggeration, use viewer functionality for that instead. | `1.0`      |
| relative_to_vertical_reference | bool               | If True, the depth of the objects in the vtm file will be with respect to a reference plane (e.g. "NAP", "Ostend height"). If False, the depth will be with respect to 0.0. The default is True.                                                                         | `True`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                                    |
|--------|------------|----------------------------------------------------------------|
|        | MultiBlock | A composite class holding the data which can be iterated over. |

### to_parquet { #geost.base.CptCollection.to_parquet }

```python
base.CptCollection.to_parquet(outfile, data_table=True, **kwargs)
```

Export the data or header table to a parquet file. By default the data table is
exported.

#### Parameters {.doc-section .doc-section-parameters}

| Name       | Type        | Description                                                                  | Default    |
|------------|-------------|------------------------------------------------------------------------------|------------|
| outfile    | str \| Path | Path to parquet file to be written.                                          | _required_ |
| data_table | bool        | If True, the data table is exported. If False, the header table is exported. | `True`     |
| **kwargs   |             | pd.DataFrame.to_parquet kwargs. See relevant Pandas documentation.           | `{}`       |

#### Examples {.doc-section .doc-section-examples}

Export the data table:

```python
>>> collection.to_parquet("example.parquet")
```

Export the header table:

```python
>>> collection.to_parquet("example.parquet", data_table=False)
```

### to_shape { #geost.base.CptCollection.to_shape }

```python
base.CptCollection.to_shape(outfile, **kwargs)
```

Write header data to shapefile. You can use the resulting file to display
borehole locations in GIS for instance.

#### Parameters {.doc-section .doc-section-parameters}

| Name     | Type        | Description                                                            | Default    |
|----------|-------------|------------------------------------------------------------------------|------------|
| outfile  | str \| Path | Path to shapefile to be written.                                       | _required_ |
| **kwargs |             | gpd.GeoDataFrame.to_file kwargs. See relevant GeoPandas documentation. | `{}`       |

### to_vtm { #geost.base.CptCollection.to_vtm }

```python
base.CptCollection.to_vtm(
    outfile
    data_columns
    radius=1
    vertical_factor=1.0
    relative_to_vertical_reference=True
    **kwargs
)
```

Save data as VTM (Multiblock file, an XML VTK file pointing to multiple other
VTK files) for viewing in external GUI software like ParaView or other VTK viewers.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type               | Description                                                                                                                                                                                                                                                              | Default    |
|--------------------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| outfile                        | str \| Path        | Path to vtm file to be written.                                                                                                                                                                                                                                          | _required_ |
| data_columns                   | str \| List\[str\] | Name or names of data columns to include for visualisation. Can be columns that contain an array of floats, ints and strings.                                                                                                                                            | _required_ |
| radius                         | float              | Radius of the cylinders in m, by default 1.                                                                                                                                                                                                                              | `1`        |
| vertical_factor                | float              | Factor to correct vertical scale. For example, when layer boundaries are given in cm, use 0.01 to convert to m. The default is 1.0, so no correction is applied. It is not recommended to use this for vertical exaggeration, use viewer functionality for that instead. | `1.0`      |
| relative_to_vertical_reference | bool               | If True, the depth of the objects in the vtm file will be with respect to a reference plane (e.g. "NAP", "Ostend height"). If False, the depth will be with respect to 0.0. The default is True.                                                                         | `True`     |
| **kwargs                       |                    | pyvista.MultiBlock.save kwargs. See relevant Pyvista documentation.                                                                                                                                                                                                      | `{}`       |