# LayeredData { #geost.base.LayeredData }

```python
base.LayeredData(self, df, has_inclined=False)
```

A class to hold layered data objects (i.e. containing "tops" and "bottoms") like
borehole descriptions which can be used for selections and exports.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type         | Description                                                                                                                                                                                           | Default    |
|--------------|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| df           | pd.DataFrame | Pandas DataFrame containing the data. Mandatory columns that must be present in the DataFrame are: "nr", "x", "y", "surface", "top" and "bottom". Otherwise, many methods in the class will not work. | _required_ |
| has_inclined | bool         | If True, the data also contains inclined objects which means the top of layers is not in the same x,y-location as the bottom of layers.                                                               | `False`    |

## Methods

| Name | Description |
| --- | --- |
| [get_cumulative_layer_thickness](#geost.base.LayeredData.get_cumulative_layer_thickness) | Get the cumulative thickness of layers where a column contains a specified search |
| [get_layer_top](#geost.base.LayeredData.get_layer_top) | Find the depth at which a specified layer first occurs. |
| [select_by_condition](#geost.base.LayeredData.select_by_condition) | Select data using a manual condition that results in a boolean mask. Returns the |
| [select_by_values](#geost.base.LayeredData.select_by_values) | Select data based on the presence of given values in a given column. Can be used |
| [slice_by_values](#geost.base.LayeredData.slice_by_values) | Slice rows from data based on matching condition. E.g. only return rows with |
| [slice_depth_interval](#geost.base.LayeredData.slice_depth_interval) | Slice data based on given upper and lower boundaries. This returns a new object |
| [to_collection](#geost.base.LayeredData.to_collection) | Create a collection from this instance of LayeredData. A collection combines |
| [to_datafusiontools](#geost.base.LayeredData.to_datafusiontools) | Export all data to the core "Data" class of Deltares DataFusionTools. Returns |
| [to_header](#geost.base.LayeredData.to_header) | Generate a :class:`~geost.base.PointHeader` from this instance of LayaredData. |
| [to_kingdom](#geost.base.LayeredData.to_kingdom) | Write data to 2 csv files: 1) interval data and 2) time-depth chart. These files |
| [to_multiblock](#geost.base.LayeredData.to_multiblock) | Create a Pyvista MultiBlock object from the data that can be used for 3D plotting |
| [to_qgis3d](#geost.base.LayeredData.to_qgis3d) | Write data to geopackage file that can be directly loaded in the Qgis2threejs |
| [to_vtm](#geost.base.LayeredData.to_vtm) | Save data as VTM (Multiblock file, an XML VTK file pointing to multiple other |

### get_cumulative_layer_thickness { #geost.base.LayeredData.get_cumulative_layer_thickness }

```python
base.LayeredData.get_cumulative_layer_thickness(column, values)
```

Get the cumulative thickness of layers where a column contains a specified search
value or values.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type               | Description                                                                | Default    |
|--------|--------------------|----------------------------------------------------------------------------|------------|
| column | str                | Name of column that must contain the search value or values.               | _required_ |
| values | str \| List\[str\] | Search value or values in the column to find the cumulative thickness for. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                               |
|--------|--------------|-----------------------------------------------------------|
|        | pd.DataFrame | Borehole ids and cumulative thickness of selected layers. |

#### Examples {.doc-section .doc-section-examples}

Get the cumulative thickness of the layers with lithology "K" in the column "lith"
use:

```python
>>> boreholes.get_cumulative_layer_thickness("lith", "K")
```

Or get the cumulative thickness for multiple selection values. In this case, a
Pandas DataFrame is returned with a column per selection value containing the
cumulative thicknesses:

```python
>>> boreholes.get_cumulative_layer_thickness("lith", ["K", "Z"])
```

### get_layer_top { #geost.base.LayeredData.get_layer_top }

```python
base.LayeredData.get_layer_top(column, values)
```

Find the depth at which a specified layer first occurs.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type               | Description                                                            | Default    |
|--------|--------------------|------------------------------------------------------------------------|------------|
| column | str                | Name of column that contains categorical data.                         | _required_ |
| values | str \| List\[str\] | Value or values of entries in the column that you want to find top of. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                                                 |
|--------|--------------|-----------------------------------------------------------------------------|
|        | pd.DataFrame | Borehole ids and top levels of selected layers in meters below the surface. |

#### Examples {.doc-section .doc-section-examples}

Get the top depth of layers in boreholes where the lithology in the "lith" column
is sand ("Z"):

```python
>>> boreholes.get_layer_top("lith", "Z")
```

### select_by_condition { #geost.base.LayeredData.select_by_condition }

```python
base.LayeredData.select_by_condition(condition, invert=False)
```

Select data using a manual condition that results in a boolean mask. Returns the
rows in the data where the 'condition' evaluates to True.

#### Parameters {.doc-section .doc-section-parameters}

| Name      | Type                          | Description                                                                                                                                                      | Default    |
|-----------|-------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| condition | list, pd.Series or array like | Boolean array like object with locations at which the values will be preserved, dtype must be 'bool' and the length must correspond with the length of the data. | _required_ |
| invert    | bool                          | If True, the selection is inverted so rows that evaluate to False will be returned. The default is False.                                                        | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                                            |
|--------|---------------------------------|------------------------------------------------------------------------|
|        | class:`~geost.base.LayeredData` | New instance containing only the data objects selected by this method. |

#### Examples {.doc-section .doc-section-examples}

Select rows in borehole data that contain a specific value:

```python
>>> boreholes.select_by_condition(boreholes["lith"]=="V")
```

Or select rows in the borehole data that contain a specific (part of) string or
strings:

```python
>>> boreholes.select_by_condition(boreholes["column"].str.contains("foo|bar"))
```

### select_by_values { #geost.base.LayeredData.select_by_values }

```python
base.LayeredData.select_by_values(column, selection_values, how='or')
```

Select data based on the presence of given values in a given column. Can be used
for example to select boreholes that contain peat in the lithology column.

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type            | Description                                                                                                                                                                                              | Default    |
|------------------|-----------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| column           | str             | Name of column that contains categorical data to use when looking for values.                                                                                                                            | _required_ |
| selection_values | str \| Iterable | Value or values to look for in the column.                                                                                                                                                               | _required_ |
| how              | str             | Either "and" or "or". "and" requires all selection values to be present in column for selection. "or" will select the core if any one of the selection_values are found in the column. Default is "and". | `'or'`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                                    |
|--------|---------------------------------|----------------------------------------------------------------|
|        | class:`~geost.base.LayeredData` | New instance containing only the data selected by this method. |

#### Examples {.doc-section .doc-section-examples}

To select boreholes where both clay ("K") and peat ("V") are present at the same
time, use "and" as a selection method:

```python
>>> boreholes.select_by_values("lith", ["V", "K"], how="and")
```

To select boreholes that can have one, or both lithologies, use or as the selection
method:

```python
>>> boreholes.select_by_values("lith", ["V", "K"], how="and")
```

### slice_by_values { #geost.base.LayeredData.slice_by_values }

```python
base.LayeredData.slice_by_values(column, selection_values, invert=False)
```

Slice rows from data based on matching condition. E.g. only return rows with
a certain lithology in the collection object.

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type            | Description                                                                                                              | Default    |
|------------------|-----------------|--------------------------------------------------------------------------------------------------------------------------|------------|
| column           | str             | Name of column that contains categorical data to use when looking for values.                                            | _required_ |
| selection_values | str \| Iterable | Values to look for in the column.                                                                                        | _required_ |
| invert           | bool            | If True, invert the slicing action, so remove layers with selected values instead of keeping them. The default is False. | `False`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                                            |
|--------|---------------------------------|------------------------------------------------------------------------|
|        | class:`~geost.base.LayeredData` | New instance containing only the data objects selected by this method. |

#### Examples {.doc-section .doc-section-examples}

Return only rows in borehole data contain sand ("Z") as lithology:

```python
>>> boreholes.slice_by_values("lith", "Z")
```

If you want all the rows that may contain everything but sand, use the "invert"
option:

```python
>>> boreholes.slice_by_values("lith", "Z", invert=True)
```

### slice_depth_interval { #geost.base.LayeredData.slice_depth_interval }

```python
base.LayeredData.slice_depth_interval(
    upper_boundary=None
    lower_boundary=None
    relative_to_vertical_reference=False
    update_layer_boundaries=True
)
```

Slice data based on given upper and lower boundaries. This returns a new object
containing only the sliced data.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type         | Description                                                                                                                                                                                                                | Default   |
|--------------------------------|--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| upper_boundary                 | float \| int | Every layer that starts above this is removed. The default is None.                                                                                                                                                        | `None`    |
| lower_boundary                 | float \| int | Every layer that starts below this is removed. The default is None.                                                                                                                                                        | `None`    |
| relative_to_vertical_reference | bool         | If True, the slicing is done with respect to any kind of vertical reference plane (e.g. "NAP", "TAW"). If False, the slice is done with respect to depth below the surface. The default is False.                          | `False`   |
| update_layer_boundaries        | bool         | If True, the layer boundaries in the sliced data are updated according to the upper and lower boundaries used with the slice. If False, the original layer boundaries are kept in the sliced object. The default is False. | `True`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                                    |
|--------|---------------------------------|----------------------------------------------------------------|
|        | class:`~geost.base.LayeredData` | New instance containing only the data selected by this method. |

#### Examples {.doc-section .doc-section-examples}

Usage depends on whether the slicing is done with respect to depth below the
surface or to a vertical reference plane.

For example, select layers in boreholes that are between 2 and 3 meters below the
surface:

```python
>>> boreholes.slice_depth_interval(2, 3)
```

By default, the method updates the layer boundaries in sliced object according to
the upper and lower boundaries. To suppress this behaviour use:

```python
>>> boreholes.slice_depth_interval(2, 3, update_layer_boundaries=False)
```

Slicing can also be done with respect to a vertical reference plane like "NAP".
For example, to select layers in boreholes that are between -3 and -5 m NAP, use:

```python
>>> boreholes.slice_depth_interval(-3, -5, relative_to_vertical_reference=True)
```

### to_collection { #geost.base.LayeredData.to_collection }

```python
base.LayeredData.to_collection(
    horizontal_reference=28992
    vertical_reference=5709
)
```

Create a collection from this instance of LayeredData. A collection combines
header and data and ensures that they remain aligned when applying methods.

#### Parameters {.doc-section .doc-section-parameters}

| Name                 | Type              | Description                                                                                                                                                                                                                                                  | Default   |
|----------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| horizontal_reference | str \| int \| CRS | EPSG of the target crs. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(), by default 28992.                                                                                                                                        | `28992`   |
| vertical_reference   | str \| int \| CRS | EPSG of the target vertical datum. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). However, it must be a vertical datum. FYI: "NAP" is EPSG 5709 and The Belgian reference system (Ostend height) is ESPG 5710, by default 5709. | `5709`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                           | Description                                    |
|--------|--------------------------------|------------------------------------------------|
|        | class:`~geost.base.Collection` | An instance of :class:`~geost.base.Collection` |

### to_datafusiontools { #geost.base.LayeredData.to_datafusiontools }

```python
base.LayeredData.to_datafusiontools(
    columns
    outfile=None
    encode=False
    relative_to_vertical_reference=True
)
```

Export all data to the core "Data" class of Deltares DataFusionTools. Returns
a list of "Data" objects, one for each data object that is exported. This list
can directly be used within DataFusionTools. If out_file is given, the list of
Data objects is saved to a pickle file.

For DataFusionTools visit:
https://bitbucket.org/DeltaresGEO/datafusiontools/src/master/

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type        | Description                                                                                                                                                                                                                                                                                                                                                                                                                      | Default    |
|--------------------------------|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| columns                        | List\[str\] | Which columns in the data to include for the export. These will become variables in the DataFusionTools "Data" class.                                                                                                                                                                                                                                                                                                            | _required_ |
| outfile                        | str \| Path | If a path to outfile is given, the data is written to a pickle file.                                                                                                                                                                                                                                                                                                                                                             | `None`     |
| encode                         | bool        | If True, categorical data columns are encoded to additional binary columns (all possible values become a seperate feature that is 0 or 1). The default is False. Warning: if there is a large number of possible categories, many columns with categorical data or both, the export process may become slow and may consume a large amount memory. Please consider carefully which categorical data columns need to be included. | `True`     |
| relative_to_vertical_reference | bool        | If True, the depth of all data objects will converted to a depth with respect to a reference plane (e.g. "NAP", "TAW"). If False, the depth will be kept as original in the "top" and "bottom" columns which is in meter below the surface. The default is True.                                                                                                                                                                 | `True`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type         | Description                                       |
|--------|--------------|---------------------------------------------------|
|        | List\[Data\] | List containing the DataFusionTools Data objects. |

### to_header { #geost.base.LayeredData.to_header }

```python
base.LayeredData.to_header(horizontal_reference=28992, vertical_reference=5709)
```

Generate a :class:`~geost.base.PointHeader` from this instance of LayaredData.

#### Parameters {.doc-section .doc-section-parameters}

| Name                 | Type              | Description                                                                                                                                                                                                                                                  | Default   |
|----------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| horizontal_reference | str \| int \| CRS | EPSG of the target crs. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(), by default 28992.                                                                                                                                        | `28992`   |
| vertical_reference   | str \| int \| CRS | EPSG of the target vertical datum. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). However, it must be a vertical datum. FYI: "NAP" is EPSG 5709 and The Belgian reference system (Ostend height) is ESPG 5710, by default 5709. | `5709`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                            | Description                                     |
|--------|---------------------------------|-------------------------------------------------|
|        | class:`~geost.base.PointHeader` | An instance of :class:`~geost.base.PointHeader` |

### to_kingdom { #geost.base.LayeredData.to_kingdom }

```python
base.LayeredData.to_kingdom(outfile, tdstart=1, vw=1500.0, vs=1600.0)
```

Write data to 2 csv files: 1) interval data and 2) time-depth chart. These files
can be imported in the Kingdom seismic interpretation software.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type        | Description                                            | Default    |
|---------|-------------|--------------------------------------------------------|------------|
| outfile | str \| Path | Path to csv file to be written.                        | _required_ |
| tdstart | int         | startindex for TDchart, default is 1                   | `1`        |
| vw      | float       | sound velocity in water in m/s, default is 1500 m/s    | `1500.0`   |
| vs      | float       | sound velocity in sediment in m/s, default is 1600 m/s | `1600.0`   |

### to_multiblock { #geost.base.LayeredData.to_multiblock }

```python
base.LayeredData.to_multiblock(
    data_columns
    radius=1
    vertical_factor=1.0
    relative_to_vertical_reference=True
)
```

Create a Pyvista MultiBlock object from the data that can be used for 3D plotting
and other spatial analyses.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type               | Description                                                                                                                                                                                                                                                              | Default    |
|--------------------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| data_columns                   | str \| List\[str\] | Name or names of data columns to include for visualisation. Can be columns that contain an array of floats, ints and strings.                                                                                                                                            | _required_ |
| radius                         | float              | Radius of the cylinders in m in the MultiBlock. The default is 1.                                                                                                                                                                                                        | `1`        |
| vertical_factor                | float              | Factor to correct vertical scale. For example, when layer boundaries are given in cm, use 0.01 to convert to m. The default is 1.0, so no correction is applied. It is not recommended to use this for vertical exaggeration, use viewer functionality for that instead. | `1.0`      |
| relative_to_vertical_reference | bool               | If True, the depth of the objects in the vtm file will be with respect to a reference plane (e.g. "NAP", "TAW"). If False, the depth will be with respect to 0.0. The default is True.                                                                                   | `True`     |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                                    |
|--------|------------|----------------------------------------------------------------|
|        | MultiBlock | A composite class holding the data which can be iterated over. |

### to_qgis3d { #geost.base.LayeredData.to_qgis3d }

```python
base.LayeredData.to_qgis3d(
    outfile
    relative_to_vertical_reference=True
    crs=None
    **kwargs
)
```

Write data to geopackage file that can be directly loaded in the Qgis2threejs
plugin. Works only for layered (borehole) data.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type              | Description                                                                                                                                                                                                                                                                | Default    |
|--------------------------------|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| outfile                        | str \| Path       | Path to geopackage file to be written.                                                                                                                                                                                                                                     | _required_ |
| relative_to_vertical_reference | bool              | If True, the depth of all data objects will converted to a depth with respect to a reference plane (e.g. "NAP", "Ostend height"). If False, the depth will be kept as original in the "top" and "bottom" columns which is in meter below the surface. The default is True. | `True`     |
| crs                            | str \| int \| CRS | EPSG of the target crs. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input().                                                                                                                                                                        | `None`     |
| **kwargs                       |                   | geopandas.GeodataFrame.to_file kwargs. See relevant Geopandas documentation.                                                                                                                                                                                               | `{}`       |

### to_vtm { #geost.base.LayeredData.to_vtm }

```python
base.LayeredData.to_vtm(
    outfile
    data_columns
    radius=1
    vertical_factor=1.0
    relative_to_vertical_reference=True
    **kwargs
)
```

Save data as VTM (Multiblock file, an XML VTK file pointing to multiple other
VTK files) for viewing in external GUI software like ParaView or other VTK viewers.

#### Parameters {.doc-section .doc-section-parameters}

| Name                           | Type               | Description                                                                                                                                                                                                                                                              | Default    |
|--------------------------------|--------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| outfile                        | str \| Path        | Path to vtm file to be written.                                                                                                                                                                                                                                          | _required_ |
| data_columns                   | str \| List\[str\] | Name or names of data columns to include for visualisation. Can be columns that contain an array of floats, ints and strings.                                                                                                                                            | _required_ |
| radius                         | float              | Radius of the cylinders in m, by default 1.                                                                                                                                                                                                                              | `1`        |
| vertical_factor                | float              | Factor to correct vertical scale. For example, when layer boundaries are given in cm, use 0.01 to convert to m. The default is 1.0, so no correction is applied. It is not recommended to use this for vertical exaggeration, use viewer functionality for that instead. | `1.0`      |
| relative_to_vertical_reference | bool               | If True, the depth of the objects in the vtm file will be with respect to a reference plane (e.g. "NAP", "TAW"). If False, the depth will be with respect to 0.0. The default is True.                                                                                   | `True`     |
| **kwargs                       |                    | pyvista.MultiBlock.save kwargs. See relevant Pyvista documentation.                                                                                                                                                                                                      | `{}`       |