# read_uullg_tables { #geost.read_uullg_tables }

```python
read_uullg_tables(
    header_table
    data_table
    horizontal_reference=28992
    vertical_reference=5709
    **kwargs
)
```

Read the header and data tables from UU-LLG boreholes (see: EasyDans KNAW) from a
local csv or parquet file into a GeoST BoreholeCollection object.

Reference dataset: https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:74935
See https://wikiwfs.geo.uu.nl/ for additional information.

## Parameters {.doc-section .doc-section-parameters}

| Name                 | Type              | Description                                                                                                                                                                                                                                                      | Default    |
|----------------------|-------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| header_table         | str \| Path       | Path to file of the UU-LLG header table.                                                                                                                                                                                                                         | _required_ |
| data_table           | str \| Path       | Path to file of the UU-LLG data table.                                                                                                                                                                                                                           | _required_ |
| horizontal_reference | str \| int \| CRS | EPSG of the data's horizontal reference. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). The default is 28992.                                                                                                                       | `28992`    |
| vertical_reference   | str \| int \| CRS | EPSG of the data's vertical datum. Takes anything that can be interpreted by pyproj.crs.CRS.from_user_input(). However, it must be a vertical datum. FYI: "NAP" is EPSG 5709 and The Belgian reference system (Ostend height) is ESPG 5710. The default is 5709. | `5709`     |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                                   | Description                                                             |
|--------|----------------------------------------|-------------------------------------------------------------------------|
|        | class:`~geost.base.BoreholeCollection` | Instance of :class:`~geost.base.BoreholeCollection` of the UU-LLG data. |