# select_points_within_polygons { #geost.spatial.select_points_within_polygons }

```python
spatial.select_points_within_polygons(gdf, polygon_gdf, buffer=0, invert=False)
```

Make a selection of point geometries based on polygon geometries and an optional
buffer.

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type                            | Description                                                                     | Default    |
|-------------|---------------------------------|---------------------------------------------------------------------------------|------------|
| gdf         | str \| Path \| gpd.GeoDataFrame | Geodataframe (or file that can be parsed to a geodataframe) to select from.     | _required_ |
| polygon_gdf | str \| Path \| gpd.GeoDataFrame | Geodataframe (or file that can be parsed to a geodataframe) to select with.     | _required_ |
| buffer      | float \| int                    | Optional buffer distance around the polygon selection geometries, by default 0. | `0`        |
| invert      | bool                            | Invert the selection, by default False.                                         | `False`    |

## Returns {.doc-section .doc-section-returns}

| Name   | Type             | Description                                       |
|--------|------------------|---------------------------------------------------|
|        | gpd.GeoDataFrame | Geodataframe containing only selected geometries. |